FROM node:alpine

WORKDIR '/app'

#RUN npm config set proxy http://192.168.100.15:80
#RUN npm config set https-proxy http://192.168.100.15:80

COPY package.json .
RUN npm install

COPY . .

CMD ["npm", "run", "start"]